DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS heater;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS usertype;

CREATE TABLE room (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL
);

CREATE TABLE heater (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	mac TEXT UNIQUE NOT NULL,
	name TEXT UNIQUE NOT NULL,
	room_fk INTEGER NOT NULL,
	last_seen TIMESTAMP,
	FOREIGN KEY (room_fk) REFERENCES room (id)
);

CREATE TABLE usertype (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL
);

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL,
	email TEXT UNIQUE NOT NULL,
	password TEXT,
	usertype_fk INTEGER NOT NULL,
	FOREIGN KEY (usertype_fk) REFERENCES usertype (id)
);

